### ISSUE TITLE
Lack of OpenGraph/Twitter Card tags

### ISSUE THREAD

**Issue by agude** [srcole/srcole.github.io#1]
Hi Scott!

I noticed your site doesn't have Twittercard or OpenGraph tags, so when it's shared on social media it just shows the URL (at least, on Twitter).

[jekyll/jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) is an easy way to add them in!

## Example of current share on Twitter

<img width="442" alt="capture" src="https://user-images.githubusercontent.com/4562016/46369155-ee19c500-c636-11e8-9313-0b30b632d2b5.PNG">

**Comment by srcole** [comment]
Good call. I'll check this out!

**Comment by srcole** [comment]
Thanks again!

After testing with the validator, looks a lot better:
![image](https://user-images.githubusercontent.com/7298871/46375088-4a84e080-c647-11e8-94a0-5e140625e653.png)

Added a few images to some posts. Will add images consistently in the future.

In the future, if I want to tweak it a bit, this post has some good tips:
https://www.brianbunke.com/blog/2017/09/06/twitter-cards-on-jekyll/
